### ISSUE TITLE
Entry Focus - All Data Entry Grids

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#110]
When pressing enter after entering data on data grids (ALL), the focus should be go to the first control.

**Comment by pasodariya** [comment]
DonePlease verify

**Comment by kvora** [comment]
Following page focus is not set...
1. User Add/Edit page

**Comment by pasodariya** [comment]
Done please verify

**Comment by kvora** [comment]
After saving the data - the focus should again go to first control - for every form - This is not done

**Comment by pasodariya** [comment]
Done Please verify
