### ISSUE TITLE
Transport Route

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#111]
- Hide, the source field.
- Increase the length of the Destination field to 100 characters
- Increase the length of the Route code to 20 characters

**Comment by mnarewec** [comment]
Also include a new field for chapter - and apply necessary functionality like other features which have chapters in them i.e. security

**Comment by AAndharia** [comment]
@kvora  Please add your questions here or discuss the same with Marsh and include further details to this task so we can estimate and raise CR.

**Comment by kvora** [comment]
@mnarewec - Every route will be from some location to some chapter in the system.. right??

**Comment by mnarewec** [comment]
Every route will be from some location to a chapter or a chapter to some location. Its the same as a student can only belong to one chapter. Several locations in a chapter, several students in a chapter.

**Comment by mnarewec** [comment]
Please provide estimates

**Comment by AAndharia** [comment]
@mnarewec  - Considering as approved as per CR spread sheet.

**Comment by mnarewec** [comment]
Yes approved

**Comment by kvora** [comment]
@mnarewec - Implemented.. will get this change in next release.

**Comment by mnarewec** [comment]
This is implemented. Thank you.
