### ISSUE TITLE
Chapters not showing up in the drop down list

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#113]
Chapters are not showing up in the drop down list of the following pages
-All concern pages under setup main menu
- All Concern pages under security main menu
- All concern pages under student main menu
- All concern pages under transport main menu

**Comment by AAndharia** [comment]
@kvora  Please include screenshot or video explaining how this work. 
@mnarewec  Please close the issue after you review this.

**Comment by kvora** [comment]
@mnarewec - Here I prepared a video to show you how one should proceed and assign chapter access rights. Hope this will help you reolve the issue -  http://screencast.com/t/UBTXiK9bekiM

**Comment by mnarewec** [comment]
Thanks. I did.
