### ISSUE TITLE
More changes to the main menus

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#117]
1. Create new main menu 'Charter Setup' and move the following sub-menus into it
   - Bus Routes
 - School Fees
 - Transport Fees

2. Rename main menu 'Setup' to 'System Setup - after move other sub-menus to 'Charter Setup', Following should remain
 - Grades, Province, Denominations, Chapters

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by AAndharia** [comment]
@mnarewec  this is a CR. I'll updated CR sheet and once approved we'll include in next release.

**Comment by mnarewec** [comment]
ok provide estimate for me to approve

**Comment by mnarewec** [comment]
@kvora Please move system setup to come before Security.

**Comment by kvora** [comment]
@mnarewec - System setup menu is before Security menu. Please verify.

**Comment by mnarewec** [comment]
Sorry Chapter Setup should come before System Setup

**Comment by kvora** [comment]
@mnarewec - This is done. You will get it in next release. Verify and close the ticket

**Comment by mnarewec** [comment]
Excellent Thank you.
