### ISSUE TITLE
Administrator User and Role

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#118]
1) Administrator User - No user, including the Administrator itself can change its role or anything else. They administrator use can just only change its password.

2) Administrator Role - The Administrator Role cannot be modified by any Role including Administrator. The Administrator role should have following permissions :
 - All the permissions under sub-menu 'Security'
- All the permissions  under sub-menu 'System Setup'

**Comment by AAndharia** [comment]
@mnarewec  this is a CR, i'll updated the CR sheet and share with you, once approved, please assign it back to us and we'll work on it.

**Comment by mnarewec** [comment]
OK. Please estimate and let me approve

**Comment by kvora** [comment]
@mnarewec 

1. As per my understanding for the suggestion in # 1 is that there will not be user edit functionality in the system. Am I right?? But what if user wants to change a user's role later or upgrade a user rights?? If we won't allow him to edit anything this will not be possible.

After login, we already have change password functionality thru which user can change his own password. So administrator user or all other user will have it from there.

2. For "Administrator" role, we will implement like we have in KSB... It won't get displayed in the list of roles. Is it fine??
