### ISSUE TITLE
Student Fee Receipt > Receipt number issue

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#132]
http://screencast.com/t/MdoRXhGB

1. There is already one receipt number "201501/00003" in database ... but in new receipt it is showing same receipt number... 

2. I am not sure how you are assigning receipt number... but if there is 0001 receipt number then next should be 0002... it directly came 0003... Please check the logic

**Comment by pasodariya** [comment]
Done Please Verify
