### ISSUE TITLE
School Fee Receipt Add/Edit should capture the School Fee Receipt details and Print Receipt

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#153]

**Comment by kvora** [comment]
@mnarewec - I am not clear about the specification here. Would you please provide me more details about exactly how you want the functionality.

**Comment by mnarewec** [comment]
@kvora 
What specifications are you not clear?

**Comment by AAndharia** [comment]
@mnarewec  according to us this is already implemented : "School Fee Receipt Add/Edit should capture the School Fee Receipt details and Print Receipt"

Can you please confirm, what's not working?

**Comment by mnarewec** [comment]
I am unable to test this functionality because when I typed a student name its now showing any details so I can move further than that.

**Comment by kvora** [comment]
@mnarewec - For fee receipt a student must be enrolled ... and to search student chapter and grade must be same as it was enrolled. Please check once and let me know.

**Comment by AAndharia** [comment]
@mnarewec  - i would suggest you to check it after new release we send. Let's keep this open for now.

**Comment by kvora** [comment]
@mnarewec - Please check in new release and close the ticket

**Comment by mnarewec** [comment]
This is really good. Please just remove the 'Grade' column during data entry.

![image](https://cloud.githubusercontent.com/assets/10192106/5958810/5cac3c9a-a814-11e4-9935-19dd1dda2610.png)

**Comment by pasodariya** [comment]
Done Please verify

**Comment by kvora** [comment]
@pasodariya - search by grade not working on fee receipt list page. Please correct the issue

**Comment by kvora** [comment]
@mnarewec - This is done. You will get it in next release.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by mnarewec** [comment]
Excellent. Thank you.
