### ISSUE TITLE
student fee receipt

### ISSUE THREAD

**Issue by jmervana** [AAndharia/ZIMS-School-Mgmt#174]
when I select user Enrollment Date , Total fee and Outstanding should be filled but it is not see screenshot:-

![image](https://cloud.githubusercontent.com/assets/7436116/5819099/3d055460-a0e1-11e4-8095-ae7d6e55417e.png)

after it when I trying to submit I got following error see screen shot below

![image](https://cloud.githubusercontent.com/assets/7436116/5819153/91699c78-a0e1-11e4-81b3-f80b19868b7e.png)

**Comment by pasodariya** [comment]
Done Please verify
