### ISSUE TITLE
Fields To Filter

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#175]
For Student Uniform Issue and Student Insurance Cover list pages, you have mentioned "Grade" as fields to filter. But those tables does not have "Grade" field. 

I have added search by chapter and student name there for now. Please let me know which fields should be used to filter the list.

**Comment by mnarewec** [comment]
I was thinking, if you know the student then you will link to his/her grade. @kvora @

**Comment by kvora** [comment]
@mnarewec - I have added Grade filter. You will get it in next release.

**Comment by mnarewec** [comment]
Thank you that has been resolved.
