### ISSUE TITLE
Student Registration Email Address

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#213]
System should accept the following type of email addresses too
![image](https://cloud.githubusercontent.com/assets/10192106/5940330/fcce50a6-a755-11e4-8168-85f87f7fbf99.png)
![image](https://cloud.githubusercontent.com/assets/10192106/5940345/0fe9ffaa-a756-11e4-973b-29b836332af8.png)

**Comment by pasodariya** [comment]
Done Please verify

**Comment by kvora** [comment]
@mnarewec - Please verify and close the ticket

**Comment by mnarewec** [comment]
Verified. Close
