### ISSUE TITLE
Student Registration not saved.

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#214]
Even though submit button is pressed, its not clearing the page and data is not saved to the database. 

This is a sure stopper @kvora @AAndharia

**Comment by pasodariya** [comment]
Done Please verify

**Comment by kvora** [comment]
@mnarewec - Please verify and close the ticket

**Comment by mnarewec** [comment]
Verified.

**Comment by mnarewec** [comment]
The issue still persist @kvora @AAndharia

**Comment by kvora** [comment]
@mnarewec New release sent to you. Please verify and close the ticket.

**Comment by mnarewec** [comment]
Resolved.
