### ISSUE TITLE
Student Registration List - long description

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#216]
Put Route Code and Province Code instead of their actual names/desc
![image](https://cloud.githubusercontent.com/assets/10192106/5958606/1315d20a-a812-11e4-9ced-eaad3b3384b0.png)

**Comment by pasodariya** [comment]
Done Please verify

**Comment by kvora** [comment]
@mnarewec - this issue is fixed and will get it in next release. Please verify and close the ticket

**Comment by mnarewec** [comment]
Resolved.
