### ISSUE TITLE
School Fee Receipt

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#61]
This feature is part of Manage Student Enrollment. When school fees are been paid, following information should be captured:

 Chapter 
 Receipt Number 
 Receipt Date
 Student ID – linked to student enrollment. 
 Amount Receipted
 Payment Type - Give option Cash, Cheque
 Payment Reference - We need to generate some ref # that we had done for student registration
 Fees Paid By

There will be student Search... Chapter, Grade, Student like we have in Student Enrollment
When user selects a student from list > Will show Student's Enrollment details
And after that Above fields to enter receipt information should be shown (Make attractive UI)

** Amount should be get deducted from Balance Outstanding **

One data is been saved in database... need to generate PDF for printing receipt...

**Comment by pasodariya** [comment]
Done Please Verify
