### ISSUE TITLE
Student Enrollment > Grade Change

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#76]
Once use has set everything... Chapter, Garde, Student.. Discount Type, Insurance and then changes Grade / Chapter... The recalculate should consider Discount and Insurance both

**Comment by kvora** [comment]
When chapter or grade change - It must not reset discount or insurance > it should consider its values for calculation.

**Comment by pasodariya** [comment]
Done Please verify
