### ISSUE TITLE
Manage Transport

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#77]
Transport Enrollment For Year {{CurrentYear}}
 Chapter - Look up from chapter table
 Student ID – Look up to student Profile (only current year enrolled students)
 Enrollment Date - From Student Enrollment table
 Grade – From Student Enrollment
 Residential Address (From Student Profile)
 Bus Route (From Student Profile) 
 Transport Fee (Automatic) 
 Term 1 Fe (25 % of Total Transport Fee) 
 Term 2 Fe (25 % of Total Transport Fee) 
 Term 3 Fe (25 % of Total Transport Fee) 
 Term 4 Fe (25 % of Total Transport Fee) 
 Balance Outstanding

**Comment by pasodariya** [comment]
Done Please verify.
