### ISSUE TITLE
Transport Fee Receipt

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#84]
This feature is part  of Manage Transport. When school fees are been paid, following information should be captured:

 Chapter 
 Receipt Number 
 Receipt Date
 Student ID – linked to student enrollment. 
 Amount Receipted
 Payment Type - Give option Cash, Cheque
 Payment Reference - 
 Fees Paid By

There will be student Search... Chapter + from Transport fee table like we have 
When user selects a student from list > Will show Student's Transport fee details
And after that Above fields to enter receipt information should be shown (UI like we have for Student fee receipt)

** Amount should be get deducted from Balance Outstanding in TransportFee**

One data is been saved in database... need to generate PDF for printing receipt...

**Comment by pasodariya** [comment]
Done Please Verify
