### ISSUE TITLE
Student fee receipt > Cancel button functionality change

### ISSUE THREAD

**Issue by kvora** [AAndharia/ZIMS-School-Mgmt#96]
When user click on cancel after saving data ask for confirmation to print receipt before cancelling

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by kvora** [comment]
Implement this for Transport fee receipt and school fee receipt

**Comment by AAndharia** [comment]
Rename "Reset" button to "New Receipt" and don't implement above mentioned functionality. "New Receipt" will just reset the form and hide "Print" button.

**Comment by pasodariya** [comment]
Done Please Verify
